# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
  # For GitHub Actions the default location (.github/workflows) can be referenced with "/"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-actions"
      
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    groups:
     dev-dependencies:
       applies-to: version-updates
       dependency-type: development
     production-dependencies:
       applies-to: security-updates
       dependency-type: production
    commit-message:
      prefix: "npm"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "
  
